### ISSUE TITLE
Can parameter values be changed after simulations are read from files?

### ISSUE THREAD

**Issue by jonrkarr** [ssandrews/Smoldyn#102]
As far as I can tell, this isn't possible. 

As a result, we've implemented model changes by (i) reading and parsing Smoldyn simulation configuration files, (ii) modifying the parse configuration, (iii) exporting the modified configuration to a file, and (iv) using Smoldyn to read the modified configuration. This could be simplified if Smoldyn retained more information from configuration files and provided additional methods to change simulation configurations.

**Comment by dilawar** [comment]
You are right. 

`simptr` is not fully exposed to Python (https://github.com/ssandrews/Smoldyn/blob/203bf3765b230fba69defdc580d3e00a71fdef26/source/python/module.cpp#L376) and most members are exposed read-only. 

`simptr` is the primary structure that that stores all information about a `Simulation`.
