### ISSUE TITLE
Strange behavior with serial numbers of 0th order reaction

### ISSUE THREAD

**Issue by formersbach** [ssandrews/Smoldyn#134]
Hey Steve,

I've encountered weird behavior concerning the serial number of particles that enter the system.
I have one 0th order reaction that adds new particles in the form 0 -> A .
Expected behavior is that new particles have a serial number that is the highest current one incremented by 1.
In my simulations the serial numbers of new particles seem to follow no pattern. 
I start with 5370 particles in my system and get the following (sorted) numbers for the new particles:
5368, 5369, 5370 (old particles), 5371, 5372, 5373, 5374, 5375, 6022, 6023, 6024, 6666, 7268, 7269, ...

Expected would be 5375, 5376, 5377 etc.

Do you have any idea what's going on here? 
If you would like to check the simulation config file to replicate the issue just let me know! 

Thanks,
Fabian

**Comment by ssandrews** [comment]
Hi Fabian,

I don't know what's causing this. You're correct that Smoldyn increments
the serial number by one every time it creates a new molecule. These
molecules can be created by being added by the user, through reactions
(reactants are discarded and products are new molecules), through species
changes at surfaces, and during porting for hybrid simulation. In addition,
and I'm not sure why I did this, when molecules desorb from a surface, a
new molecule is created and the serial number from the original molecule is
copied over into the new molecule; this is invisible to the user except
that the serial number counter gets incremented in the process. This last
process may be causing the behavior that you're observing. In general,
there is a guarantee that every molecule in a simulation has a unique
serial number, but there is no promise that they will increase sequentially.

If the cause of what you're observing appears to arise from the desorption
process and if this is a problem for your work, let me know. I could
probably change this fairly easily.

Cheers,
-Steve

**Comment by formersbach** [comment]
Hey Steve,

Does that mean that even when I redefine how the reaction serial number is assigned it is still incremented by one?

To put what I mean into an example:
A (1) + B (2) -> AB (1.2) 
Serial numbers indicated in brackets, using r1.r2 as the reaction serial number rule for the products.
Now even though the new particle AB gets assigned 1.2 as its serial number, when I add a new molecule it will get serial number 4 not 3. 
Naively I would expect the new particle to get serialnum 3.

Did I get that right?
If so, then that is likely what's going on. 
Best,
Fabian

**Comment by ssandrews** [comment]
Hi Fabian,

That’s probably what’s happening. Whenever Smoldyn gets a new molecule, it
gives it a serial number and increments the counter. It then overwrites the
serial number in your case, but doesn’t reset the counter. Again, this
could be changed if it’s important to you, but I was expecting that people
wouldn’t care about particular serial number values.

-Steve

**Comment by formersbach** [comment]
Hey Steve,

I see, thanks a lot! It's not an issue for me, but it might be something worth mentioning in the manual for the reaction_serialnum command. 
I'll close the issue if that's okay.

Best,
Fabian
