### ISSUE TITLE
tag releases on github as well?

### ISSUE THREAD

**Issue by alexmyczko** [ssandrews/Smoldyn#4]
would that be possible somehow?

just to let you know, i'm working on a debian package:
http://phd-sid.ethz.ch/debian/smoldyn/

could you drop these files from tarball releases?
```
W: smoldyn source: source-contains-prebuilt-windows-binary source/MinGWlibs/freeglut/bin/freeglut.dll
W: smoldyn source: source-contains-prebuilt-windows-binary source/MinGWlibs/freeglut/bin/x64/freeglut.dll
```

and remove the executable bit on these?
See https://github.com/ssandrews/Smoldyn-official/pull/5

do you have source files for the *.pdf files under documentation?

**Comment by dellelce** [comment]
@ssandrews any feedback on this best practice suggestion?

**Comment by ssandrews** [comment]
Hi,

Sorry for not replying earlier!  Also, thanks for working on a Debian
package.  There are already some Smoldyn versions for Linux, but I don't
recall what's available at the moment.  Regarding releases, my system has
been to archive all of the Smoldyn code on the github site, but then to use
www.smoldyn.org as the primary place for releases.  Would it be helpful if
I put the release tar files on github as well?  I have lots of programming
experience, but I'm still a beginner when it comes to github.

Cheers,
-Steve

**Comment by alexmyczko** [comment]
Hi Steve,

Here's a list of linux distributions that have smoldyn: https://repology.org/project/smoldyn/versions

Yes it'd be great to have tar files on github as well!

**Comment by dilawar** [comment]
@alexmyczko Thanks for repology: interesting project.

I maintain Linux packages for Smoldyn in my personal repository here https://software.opensuse.org//download.html?project=home%3Adilawar&package=smoldyn . It seems that repology does not crawl personal projects on Open Build Service.

**Comment by ssandrews** [comment]
Thanks for suggesting tagging. I finally made the first tag, which is also the first release in a very long time. Hopefully, I can keep up better in the future.
