### ISSUE TITLE
Add tokens for pushing Smoldyn to BioSimulators

### ISSUE THREAD

**Issue by jonrkarr** [ssandrews/Smoldyn#74]
Two tokens need to be saved as "secrets" to enable the GitHub Action workflows to push Smoldyn to BioSimulators

1. Create a GitHub personal access token for this purpose at https://github.com/settings/tokens/new. Check these scopes:
    -  `public_repo`
    -  `write:packages`
 2. Save the new token as a "secret" at https://github.com/ssandrews/Smoldyn/settings/secrets/actions/new
    - Name: `BIOSIMULATORS_GH_TOKEN`
    - Value: `{personal access token}`
3. Save a second secret with the GitHub user name associated with this token
   - Name: `BIOSIMULATORS_GH_USERNAME`
    - Value: `ssandrews`

**Comment by ssandrews** [comment]
Tokens and secrets are created.
