### ISSUE TITLE
Enable GitHub Container Registry

### ISSUE THREAD

**Issue by jonrkarr** [ssandrews/Smoldyn#76]
@ssandrews can you enable Enable GitHub Container Registry (GHCR) for the repository? GHCR is similar to DockerHub, but avoids having to deal with a separate account. This will allow us to save the Docker image so others can pull it without having to build it themselves.

These screenshots show how to enable GHCR

![image](https://user-images.githubusercontent.com/2848297/119758623-d2f9c480-be74-11eb-9839-446eff531e98.png)

![image](https://user-images.githubusercontent.com/2848297/119758635-d8570f00-be74-11eb-833d-0f8c10c8ab28.png)

**Comment by ssandrews** [comment]
Ok. It's enabled.
