### ISSUE TITLE
Make Docker image public

### ISSUE THREAD

**Issue by jonrkarr** [ssandrews/Smoldyn#77]
The Docker image I created seems to have been pushed successfully, but I can't see it. I think it must be private. @ssandrews can you make it public?

I think you should be able to see the package (ssandrews/smoldyn/biosimualtors_smoldyn) here: https://github.com/ssandrews?repo_name=Smoldyn&tab=packages

I think the setting is under "Package settings" >> "Change package visibility".

**Comment by ssandrews** [comment]
I can view the packages just fine, and it confirms that
smoldyn/biosimulators_smoldyn package is private, but I simply can't find
any "package settings" option or any other way to change the package from
private to public. Sorry to not be more helpful here. If you can figure it
out, let me know. Perhaps I don't have admin privileges for this package,
but that would be strange.

**Comment by jonrkarr** [comment]
Thanks for taking care of this so fast! I just have a couple things left to get Smoldyn online. I'll email when its ready.

I think the setting should be at the bottom of this page ("Change package visibility")
https://github.com/users/ssandrews/packages/container/smoldyn%2Fbiosimulators_smoldyn/settings

![image](https://user-images.githubusercontent.com/2848297/119868808-87373180-beed-11eb-93fa-e71a75d92f08.png)

**Comment by ssandrews** [comment]
Thank you! I searched everywhere for that web page but couldn't seem to get
to it.

**Comment by jonrkarr** [comment]
I like GHCR now, but I also found it a bit non-intuitive at first. Its still a beta feature of GitHub.
