### ISSUE TITLE
Tarball for 2.65 changed on 

### ISSUE THREAD

**Issue by yurivict** [ssandrews/Smoldyn#86]
```
=> Attempting to fetch http://www.smoldyn.org/smoldyn-2.65.tgz
fetch: http://www.smoldyn.org/smoldyn-2.65.tgz: size mismatch: expected 30318941, actual 30399811
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/smoldyn-2.65.tgz
fetch: http://distcache.FreeBSD.org/ports-distfiles/smoldyn-2.65.tgz: Not Found
```

Was it replaced for the same version number?

**Comment by ssandrews** [comment]
Hi,

Yes, it was. I didn't realize that it would cause problems. I found some
tiny correction that I wanted to make, so I just uploaded the corrected
version with the same version number. Sorry about that!

Did the download work for you in the end?

-Steve

**Comment by yurivict** [comment]
> Did the download work for you in the end?

Yes, thank you.

**Comment by ssandrews** [comment]
That's great to hear. Let me know if you have further questions.

-Steve
